// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HeapShot.Gui {
    
    
    public partial class SelectProcessDialog {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView list;
        
        private Gtk.Label label2;
        
        private Gtk.Button button1;
        
        private Gtk.Button button8;
        
        protected virtual void Build() {
            // Widget HeapShot.Gui.SelectProcessDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "HeapShot.Gui.SelectProcessDialog";
            this.Title = "Select process";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child HeapShot.Gui.SelectProcessDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(12));
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = "Select a process:";
            this.vbox1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.VscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.list = new Gtk.TreeView();
            this.list.CanFocus = true;
            this.list.Name = "list";
            this.scrolledwindow1.Add(this.list);
            this.vbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
            w4.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.WidthRequest = 492;
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = "<b>Warning:</b> Memory snapshots can only be taken from mono processes started with the option \"--profile=heap-shot\". If you select a process which was not started using this option, the process will be stopped.";
            this.label2.UseMarkup = true;
            this.label2.Wrap = true;
            this.vbox1.Add(this.label2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.label2]));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            w1.Add(this.vbox1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w1[this.vbox1]));
            w6.Position = 0;
            // Internal child HeapShot.Gui.SelectProcessDialog.ActionArea
            Gtk.HButtonBox w7 = this.ActionArea;
            w7.Events = ((Gdk.EventMask)(256));
            w7.Name = "HeapShot.Gui.SelectProcessDialog_ActionArea";
            w7.Spacing = 10;
            w7.BorderWidth = ((uint)(5));
            w7.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child HeapShot.Gui.SelectProcessDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanDefault = true;
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseStock = true;
            this.button1.UseUnderline = true;
            this.button1.Label = "gtk-cancel";
            this.AddActionWidget(this.button1, -6);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.button1]));
            w8.Expand = false;
            w8.Fill = false;
            // Container child HeapShot.Gui.SelectProcessDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button8 = new Gtk.Button();
            this.button8.CanDefault = true;
            this.button8.CanFocus = true;
            this.button8.Name = "button8";
            this.button8.UseStock = true;
            this.button8.UseUnderline = true;
            this.button8.Label = "gtk-ok";
            this.AddActionWidget(this.button8, -5);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.button8]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 531;
            this.DefaultHeight = 425;
            this.Show();
            this.Response += new Gtk.ResponseHandler(this.OnResponse);
        }
    }
}
