
// This file has been generated by the GUI designer. Do not modify.
namespace HeapShot.Gui.Widgets
{
	public partial class ReferenceTreeViewer
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TreeView treeview;
		private global::Gtk.HBox hbox1;
		private global::Gtk.HBox boxFilter;
		private global::Gtk.Entry entryFilter;
		private global::Gtk.Button buttonFilter;
		private global::Gtk.CheckButton checkInverse;
		private global::Gtk.CheckButton checkPurge;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HeapShot.Gui.Widgets.ReferenceTreeViewer
			global::Stetic.BinContainer.Attach (this);
			this.Events = ((global::Gdk.EventMask)(256));
			this.Name = "HeapShot.Gui.Widgets.ReferenceTreeViewer";
			// Container child HeapShot.Gui.Widgets.ReferenceTreeViewer.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView ();
			this.treeview.CanFocus = true;
			this.treeview.Events = ((global::Gdk.EventMask)(8196));
			this.treeview.Name = "treeview";
			this.scrolledwindow1.Add (this.treeview);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.boxFilter = new global::Gtk.HBox ();
			this.boxFilter.Name = "boxFilter";
			this.boxFilter.Spacing = 3;
			// Container child boxFilter.Gtk.Box+BoxChild
			this.entryFilter = new global::Gtk.Entry ();
			this.entryFilter.CanFocus = true;
			this.entryFilter.Name = "entryFilter";
			this.entryFilter.IsEditable = true;
			this.entryFilter.InvisibleChar = '●';
			this.boxFilter.Add (this.entryFilter);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.boxFilter [this.entryFilter]));
			w3.Position = 0;
			// Container child boxFilter.Gtk.Box+BoxChild
			this.buttonFilter = new global::Gtk.Button ();
			this.buttonFilter.Sensitive = false;
			this.buttonFilter.CanFocus = true;
			this.buttonFilter.Name = "buttonFilter";
			this.buttonFilter.Label = "Filter";
			this.boxFilter.Add (this.buttonFilter);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.boxFilter [this.buttonFilter]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox1.Add (this.boxFilter);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.boxFilter]));
			w5.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkInverse = new global::Gtk.CheckButton ();
			this.checkInverse.Sensitive = false;
			this.checkInverse.CanFocus = true;
			this.checkInverse.Name = "checkInverse";
			this.checkInverse.Label = "Inverse references";
			this.checkInverse.DrawIndicator = true;
			this.hbox1.Add (this.checkInverse);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkInverse]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkPurge = new global::Gtk.CheckButton ();
			this.checkPurge.Sensitive = false;
			this.checkPurge.CanFocus = true;
			this.checkPurge.Name = "checkPurge";
			this.checkPurge.Label = global::Mono.Unix.Catalog.GetString ("Roots only");
			this.checkPurge.DrawIndicator = true;
			this.checkPurge.UseUnderline = true;
			this.hbox1.Add (this.checkPurge);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkPurge]));
			w7.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.treeview.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnTreeviewMotionNotifyEvent);
			this.treeview.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler (this.OnTreeviewLeaveNotifyEvent);
			this.entryFilter.Activated += new global::System.EventHandler (this.OnEntryFilterActivated);
			this.buttonFilter.Clicked += new global::System.EventHandler (this.OnButtonFilterClicked);
			this.checkInverse.Clicked += new global::System.EventHandler (this.OnCheckInverseClicked);
			this.checkPurge.Clicked += new global::System.EventHandler (this.OnCheckPurgeClicked);
		}
	}
}
